name: CI/CD Pipeline

on:
  push:
    branches: [master, main, develop]
  pull_request:
    branches: [master, main, develop]

jobs:
  test-backend:
    name: Test Backend (.NET)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/backend/RestaurantApp.sln

      - name: Build
        run: dotnet build src/backend/RestaurantApp.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test src/backend/RestaurantApp.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: '**/coverage.cobertura.xml'
          flags: backend

  test-frontend:
    name: Test Frontend (React)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/frontend/package-lock.json

      - name: Install dependencies
        working-directory: src/frontend
        run: npm ci

      - name: Lint
        working-directory: src/frontend
        run: npm run lint

      - name: Run tests
        working-directory: src/frontend
        run: npm run test:coverage

      - name: Build
        working-directory: src/frontend
        run: npm run build

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: src/frontend/coverage/coverage-final.json
          flags: frontend

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Backend Image
        uses: docker/build-push-action@v5
        with:
          context: src/backend
          push: false
          tags: restaurant-backend:latest

      - name: Build Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: src/frontend
          push: false
          tags: restaurant-frontend:latest
